### ISSUE TITLE
Cannot setup camera

### ISSUE THREAD

**Issue by GotSpokeNeedHub** [nod5/TwoCamControl#2]
I am excited to use your software in a diy bookscanner project and while trying to connect two Canon ELPH160 cameras I am not able to setup the "Right cam serial" via the application.

When using cli "chdkptp.exe -elist"  I get a blank line and returned to the command prompt.

Is there a diagnostic command / log I can submit that may help?

**Comment by nod5** [comment]
If `chdkptp.exe -elist` has no effect then you may need to reinstall LibUSB for that camera.
See http://chdk.wikia.com/wiki/PTP_Extension#LibUSB_Driver_for_Windows
In my experience some Windows 10 updates may remove the LibUSB installation.
