### ISSUE TITLE
zooming results in different zooms for each camera

### ISSUE THREAD

**Issue by meelash** [nod5/TwoCamControl#3]
I've noticed that I am not getting the same zoom level on each camera. For example, starting up with 2 zoom steps each, each camera zooms twice (can tell from the noise and by watching) but will end up at different zoom levels.

I believe this is because using
`click('zoom_in')`
does not guarantee the length of time that click is pressed. "Momentarily" pressed does not seem to necessarily be the same thing.

Instead of this, what needs to be used to guarantee the same zoom level for each camera is:
`get_zoom_steps from: http://chdk.wikia.com/wiki/Script_commands`
to get the full range for the connected camera. Depending on how fine control is wanted an arbitrary zoom steps can be converted into a fraction from 0-1 and multiplied by get_zoom_steps and rounded to a whole number to get the desired zoom step from the connected camera.
use:
`set_zoom(x) from: http://chdk.wikia.com/wiki/UBASIC/TutorialScratchpad`

For example, if we have 20 zoom steps, then setting to zoom 15 would do this:
`
zoom_factor = 15 * (1/20)`
`desired_zoom = round_to_nearest_whole_number(get_zoom_steps() * zoom_factor)`
`set_zoom(desired_zoom)
`

**Comment by meelash** [comment]
This will also prevent undesirable/unpredictable results if the number of zoom steps is beyond the cameras range.

**Comment by meelash** [comment]
The preset zoom steps on connection can use the factor as shown above to calculate desired zoom and the buttons for manually zooming in and out could use:
`set_zoom_rel `

**Comment by nod5** [comment]
Thanks for the detailed feedback. I hadn't noticed this because I use/test with two same model cameras. 
Will fix, but short on time ATM.

**Comment by meelash** [comment]
Thanks for your quick response.

I also actually have two same model cameras, but still had the problem. It may depend on the model of the camera or its firmware how it responds to click(), I guess, or maybe the problem only becomes apparent in cameras with more or less possible zoom steps.
Fortunately, since we can just type directly into the command windows, I can confirm that it is actually resulting in different zoom steps and not some other problem the next time I do a scan. If it turns out to not be what I think it is, I will update here.

It should also be simple to workaround for now by just zooming to the desired zoom in the command window.

**Comment by meelash** [comment]
So just in terms of an **update**:

I can confirm that the problem is the non-guaranteed nature of click('zoom_in'). When running the following commands in sequence:
```
= click('zoom_in')
=return get_zoom()
= click('zoom_out')
= click('zoom_in')
=return get_zoom()
```
the consecutive get_zoom's return different values.

The **workaround** is to not use twocamcontrol's zoom system, rather manually zoom in and out in the command windows using `= set_zoom_rel(x)` where x is positive or negative integer for zoom steps. When you confirm with the preview that the setting is correct, use `=return get_zoom()` to determine the zoom steps value. Following that, whenever starting twocamcontrol, type `= set_zoom(y)` in each window where y is your zoom steps value.

**Comment by nod5** [comment]
Thanks again. I have now reproduced the issue using two cameras of the same model.

The deviations are quite small for my cameras so I didn't notice them before reading the `get_zoom()` output.

I'm mulling over how to best implement a fix in TwoCamControl. There are two use cases to consider.  
**User1**: wants to autozoom to the same exact zoom position each time the cameras connect.
**User2**: wants to connect cameras and then manually stepwise zoom and check LCD/preview until they reach a good zoom position, which may vary between sessions.

The question is what TwoCamControl's `Zoom` button should do. Alternatives:
1. `click('zoom_in')`. Current implementation. Has the small deviation problem. Which may not be a practical problem for some users.
2. `set_zoom_rel("+1")`. Solves the deviation problem. But impractical for User2 on cameras with a 128 zoom step range. Too many button presses!
3. zoom X percent of each camera's total zoom range. For example with X=5% and a 128 step zoom range camera we do `set_zoom_rel("+6")`.

I could keep 1 as default but add a dropdown menu to settings where users can switch to 2 or 3.
Another alternative is to change the GUI from a zoom button to some other control like a slider, input, dropdown, ... 

What do you think?

Note to self: We can access `get_zoom()` and `get_zoom_steps()` values from AutoHotkey by writing (and later reading) a temporary text file, like so
```
!var = con:execwait('return get_zoom_steps()')
!file = io.open("zoom_steps.txt", "w")
!file:write(tostring(var))
!file:close()
```

**Comment by nod5** [comment]
Try release 2018-08-30

**Comment by nod5** [comment]
Some disadvantages with set_zoom were discovered.  
See https://github.com/nod5/TwoCamControl/blob/master/docs/notes_on_zoom_methods.md for details.  
Release 2018-10-03 uses set_zoom as default but has an option to use the non-default click('zoom_in') method.
