### ISSUE TITLE
zoom error in 03-10-2018 release

### ISSUE THREAD

**Issue by bartek158** [nod5/TwoCamControl#5]
Hello
I recognize zoom error wchich appear only when I use zoom option.

connected: Canon PowerShot A2500 , max packet size 512
con 1> !var = con:execwait('return get_zoom_steps()')
con 2> !file = io.open('twocamcontrol_zoom_temp.txt', 'w')
con 2> !file:write(tostring(var))
con 2> !file:close()
con 2> luar set_zoom('1')
ERROR: I/O error
___>

Best Regards

**Comment by nod5** [comment]
Starting with version 2018-08-26 TwoCamControl uses a different zoom method as default. 
The new default zoom method is more exact but may not work with all cameras. Details [here](https://github.com/nod5/TwoCamControl/blob/master/docs/notes_on_zoom_methods.md).

To find out if that is the problem try these things:
- What versions of CHDK firmware and chdkptp are you using? If not the latest, try updating and see if that fixes the problem.
- Connect the camera to chdkptp manually (without TWoCamControl) and then try the command 
`luar set_zoom('1')`
Does that still return `ERROR: I/O error`?
- Does `luar set_zoom('5')` also return `ERROR: I/O error`?

You can also try the "alt zoom" checkbox in the TwoCamControl Setup tab. When that is checked TwoCamControl uses the old zoom method from versions before 2018-08-26. Does zoom work in that mode?

edit: corrected the luar code snippets above to include single quotes around the digit.

**Comment by bartek158** [comment]
I was using CHDKPTP 690. I instal the latest version chdkptp-r795-win32.zip the problem still exist. 
I use zadig to upgrade sd card firmware but actually is still the same version 100a ( 1.3 stable) like two years ago.
IN CHDKPTP there is no problem to use command:
luar set_zoom('1')
luar set_zoom('2')
but the problem is when zoom is '3' or more. Then apperar ERROR: I/O error.

**Comment by nod5** [comment]
Thanks for these details. However I don't know why set_zoom works for values 1 and 2 but not 3 or more on your cameras (model A2500 you wrote in another issue) so I don't know how to fix the issue. You could ask about that set_zoom issue in the A2500 firmware thread in CHDK forums.

In the meantime try using the "alt zoom" checkbox in the TwoCamControl Setup tab. When that is checked TwoCamControl uses the old zoom method from versions before 2018-08-26. Does zoom work ok in that mode?

**Comment by bartek158** [comment]
Witch "alt zoom" works ok.

**Comment by nod5** [comment]
> "alt zoom" works ok.

Ok, good. 

> I use zadig to upgrade sd card firmware but actually is still the same version 100a ( 1.3 stable) like two years ago.

Are you certain you use the lastest firmware? You wrote 1.3 stable, but the below are as of now the latest versions on the CHDK download page for A2500.

development version (use that!):  
http://mighty-hoernsche.de/trunk/bins/a2500-100a-1.5.0-5122-full_ALPHA.zip  

stable version:  
http://mighty-hoernsche.de/bins/a2500-100a-1.4.1-5097-full_ALPHA.zip

**Comment by bartek158** [comment]
I use to instal a2500 frimvare stick software but I can instal only whot stick download automaticly. From development version i can only choose betwen 1.4 and 1.4 DE version. Download file is inactiv, ( before and after I drop photo to stick)
![stick](https://user-images.githubusercontent.com/44677349/49930637-51409700-fec5-11e8-9b1a-cbaa6f292aec.jpg)

**Comment by bartek158** [comment]
How to instal firmware from file ( not this whot stick download) ?

**Comment by bartek158** [comment]
I instal latest wersion 1,5  5139 and zoom works ok :) 
Thanks for help :)

**Comment by nod5** [comment]
Ok, great that it is working with that firmware version. Then I can close this issue.
