### ISSUE TITLE
F8 doesn't work

### ISSUE THREAD

**Issue by bartek158** [nod5/TwoCamControl#7]
Hello
I use chdkptp 795 32win , win10 64bit polish language, 100a sd card chdk firmware, two Canon A2500.
IN my case the previous version when I use F8 key make that in comand line appear previous command.
In 2018-11-07 TCC version F8 key doesn't work , i mean nothing heppend when I use it. Meyby it is some windows problem  ? I use my laptop only for book scaning , I don't make any changes in windows configuration, mayby it heppen during windows update.

Best Regards

**Comment by nod5** [comment]
Thanks for reporting. I made a small error in the F8 code in 2018-11-07. Fixed in version 2018-11-13.

**Comment by bartek158** [comment]
Thanks a lot :)

**Comment by nod5** [comment]
Fixed in version 2018-11-13.
